name: Clean Up Stale Reviews

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run cleanup script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BIOC_ORG_TOKEN: ${{ secrets.BIOC_ORG_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          TEMP_BIOC_TOKEN: ${{ secrets.TEMP_BIOC_TOKEN }}
          GIT_TARGET_ORG: "tempbioc"
        run: |
          python scripts/check_stale_reviews.py


