name: Manually Assign Package Reviewer

on:
  issues:
    types: [labeled]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest

    # Only run if the label added is "assign reviewer"
    if: ${{ github.event.label.name == 'assign reviewer' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for branch switching

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Assign reviewer from PackageReviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: Bioconductor
          TEAM_SLUG: packagereviewers    # GitHub team slug, always lowercase
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          EXCLUDED_REVIEWERS: ${{ secrets.EXCLUDED_REVIEWERS }}
	  REVIEWER_STATE_PATH: submissions/last_assignee.txt
          TARGET_GITHUB_TOKEN: ${{ secrets.TARGET_GITHUB_TOKEN }}
        run: python scripts/assign-reviewer.py